apiVersion: v1
kind: Service
metadata:
  name: taskboard-backend
  namespace: taskboard
spec:
  type: ClusterIP
  selector:
    app: taskboard-backend
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
